version: '2.1'

services:
    rt1:
        command: tcpdump -nSt icmp
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
    rt2:
        command: ping -s 4000 rt1
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
        depends_on:
            - rt1
    rt3:
        command: ping rt1
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
        sysctls:
          - net.ipv4.icmp_echo_ignore_all=1
        depends_on:
            - rt1
    rt4:
        command: ping -c 1 rt3
        image: tema1:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet2
        depends_on:
            - rt3
    tn1:
        command: bash -c 'echo \"- interfetele de retea:\" && ip addr && echo \"- gateway:\" && ip route show'
        image: baseimage:latest
        volumes:
            - .:/elocal
        tty: true
        networks:
            - tnet1
networks:
    tnet2:
        ipam:
            driver: default
            config:
                - subnet: 1.2.3.0/16
                  gateway: 1.2.3.4
    tnet1:
        ipam:
            driver: default
            config:
                - subnet: 78.42.7.0/30
                  gateway: 78.42.7.1
